name: oneshot-face
channels:
- pytorch-nightly
- conda-forge
- pip
dependencies:
- python=3.9
- conda-forge::nb_conda_kernels
- pip
- scikit-image
- scikit-learn
- numpy
- matplotlib
- onnxruntime
- pytorch-nightly::pytorch
- pytorch-nightly::torchvision
- mlflow
- pandas
- lightning
- seaborn
- pip:
  - pip_search
  - skl2onnx
  - luwiji
  - jcopml
  - jcopdl
  - dvc
variables:
  MLFLOW_TRACKING_USERNAME: izzalDev
  MLFLOW_TRACKING_URI: https://dagshub.com/izzalDev/oneshot-face.mlflow
